"""empty message

Revision ID: 277dcb264a89
Revises: 5ed36a561ac1
Create Date: 2025-12-13 00:50:30.301080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '277dcb264a89'
down_revision = '5ed36a561ac1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('session_device', schema=None) as batch_op:
        batch_op.drop_column('custom_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_name', mysql.VARCHAR(length=256), nullable=True))

    op.drop_table('user_follow_author')
    op.drop_table('user_follow_user')
    op.drop_table('community_follower')
    # ### end Alembic commands ###
