"""empty message

Revision ID: 3a39b54af75c
Revises: bff0c489c9ee
Create Date: 2025-12-07 17:58:50.731532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a39b54af75c'
down_revision = 'bff0c489c9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_follower', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('community_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('data_set_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('data_set_ibfk_3'), 'community', ['community_id'], ['id'])

    with op.batch_alter_table('community_follower', schema=None) as batch_op:
        batch_op.alter_column('community_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
