"""create_session_model

Revision ID: 5ed36a561ac1
Revises: 3a39b54af75c
Create Date: 2025-12-12 00:45:24.881846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed36a561ac1'
down_revision = '3a39b54af75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=100), nullable=False),
    sa.Column('custom_name', sa.String(length=256), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_device')
    # ### end Alembic commands ###
