"""empty message

Revision ID: 746070cea963
Revises: c554366a1bd0
Create Date: 2025-11-29 23:26:06.303700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746070cea963'
down_revision = 'c554366a1bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follow_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follow_user')
    # ### end Alembic commands ###
