"""empty message

Revision ID: 7a9e02fd06b1
Revises: fd85db1605ac
Create Date: 2025-11-08 20:17:25.619073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a9e02fd06b1'
down_revision = 'fd85db1605ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comp_filename', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('comp_version', sa.String(length=120), nullable=True))
        batch_op.drop_column('uvl_filename')
        batch_op.drop_column('uvl_version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('comp_version')
        batch_op.drop_column('comp_filename')

    # ### end Alembic commands ###
