"""empty message

Revision ID: 7a9e02fd06b1
Revises: fd85db1605ac
Create Date: 2025-11-08 20:17:25.619073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '7a9e02fd06b1'
down_revision = 'fd85db1605ac'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    columns = [col["name"] for col in inspector.get_columns("fm_meta_data")]
    
    # Para cada columna se comprueba si existe o no en la base de datos para evitar intentar volver a crearla
    if "comp_filename" not in columns:
        with op.batch_alter_table("fm_meta_data") as batch_op:
            batch_op.add_column(sa.Column("comp_filename", sa.String(120), nullable=False))

    if "comp_version" not in columns:
        with op.batch_alter_table("fm_meta_data") as batch_op:
            batch_op.add_column(sa.Column("comp_version", sa.String(120)))

    if "uvl_filename" in columns:
        with op.batch_alter_table("fm_meta_data") as batch_op:
            batch_op.drop_column("uvl_filename")

    if "uvl_version" in columns:
        with op.batch_alter_table("fm_meta_data") as batch_op:
            batch_op.drop_column("uvl_version")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('comp_version')
        batch_op.drop_column('comp_filename')

    # ### end Alembic commands ###
