"""replace feature_model with comp_model

Revision ID: 9196c8aeba12
Revises: 
Create Date: 2025-12-13 01:18:52.690033
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9196c8aeba12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear tablas nuevas
    op.create_table('community_follower',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('community_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['community_id'], ['community.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_follow_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('follower_id', sa.Integer(), nullable=False),
        sa.Column('followed_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['followed_id'], ['user.id']),
        sa.ForeignKeyConstraint(['follower_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('comp_model',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data_set_id', sa.Integer(), nullable=False),
        sa.Column('fm_meta_data_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id']),
        sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('user_follow_author',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['author.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Desactivar FKs, eliminar columna y tabla antigua
    op.execute("SET FOREIGN_KEY_CHECKS=0")

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('file_ibfk_1', type_='foreignkey')
        batch_op.drop_column('feature_model_id')
        batch_op.add_column(sa.Column('comp_model_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'comp_model', ['comp_model_id'], ['id'])

    op.drop_table('feature_model')

    op.execute("SET FOREIGN_KEY_CHECKS=1")
    # ### end Alembic commands ###


def downgrade():
    # ### revertir cambios ###
    op.execute("SET FOREIGN_KEY_CHECKS=0")

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comp_model_id')
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('file_ibfk_1', 'feature_model', ['feature_model_id'], ['id'])

    op.create_table('feature_model',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name='feature_model_ibfk_1'),
        sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name='feature_model_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )

    op.drop_table('user_follow_author')
    op.drop_table('comp_model')
    op.drop_table('user_follow_user')
    op.drop_table('community_follower')

    op.execute("SET FOREIGN_KEY_CHECKS=1")
    # ### end Alembic commands ###
