# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNotepadcreate():
  
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_notepadcreate(self):
        self.driver.get("http://localhost:5000/login?next=%2Fnotepad")
        self.driver.set_window_size(706, 923)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1234")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(3)").click()
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("Prueba")
        self.driver.find_element(By.ID, "body").click()
        self.driver.find_element(By.ID, "body").send_keys("Prueba")
        self.driver.find_element(By.CSS_SELECTOR, ".content").click()
        self.driver.find_element(By.ID, "submit").click()